# Generated by Django 5.2.8 on 2025-11-30 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_highriskzone_policeofficer_dispatchtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policeofficer',
            options={},
        ),
        migrations.RemoveField(
            model_name='dispatchtask',
            name='arrived_at',
        ),
        migrations.RemoveField(
            model_name='policeofficer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='policeofficer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='policeofficer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policeofficer',
            name='rank',
            field=models.CharField(default='Officer', max_length=50),
        ),
        migrations.AddField(
            model_name='policeofficer',
            name='station',
            field=models.CharField(default='Main Station', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispatchtask',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='emergency.policeofficer'),
        ),
        migrations.AlterField(
            model_name='policeofficer',
            name='badge_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='policeofficer',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline'), ('en_route', 'En Route'), ('on_scene', 'On Scene')], default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='policeofficer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
