# Generated by Django 5.2.8 on 2025-12-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0006_alter_emergencycontact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyalert',
            name='alert_type',
            field=models.CharField(blank=True, choices=[('manual', 'Manual Trigger'), ('automatic', 'Automatic Detection'), ('panic', 'Panic Button')], default='panic', max_length=20),
        ),
    ]
