# Generated by Django 5.2.8 on 2025-11-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('regular_user', 'Regular User'), ('mobile_officer', 'Mobile Officer'), ('admin', 'Admin')], default='regular_user', max_length=20),
        ),
    ]
